#!/bin/bash




if [ $2 ]
then
	VAL=$2
else
	VAL=10
fi

if [ $1 == "dec" ]
then
	NEW=$(expr $(cat /sys/class/backlight/amdgpu_bl0/brightness) - $VAL )
	
	if [ $NEW -lt "10" ] 
	then 
		echo "too low"
	else
		echo $NEW > /sys/class/backlight/amdgpu_bl0/brightness
	fi
	echo $(cat /sys/class/backlight/amdgpu_bl0/brightness)
else
if [ $1 == "inc" ]
then
	NEW=$(expr $(cat /sys/class/backlight/amdgpu_bl0/brightness) + $VAL )
	if [ $NEW -gt "150" ] 
	then 
		echo "too high"
	else
		echo  $NEW > /sys/class/backlight/amdgpu_bl0/brightness
	fi
	
fi
fi

TEXT="$(cat /sys/class/backlight/amdgpu_bl0/brightness)"
ID=$(cat /home/brian/.config/.dunst_backlight)
ICON="/usr/share/icons/breeze-dark/actions/24/contrast.svg"
if [ $ID -gt "0" ]
then
 dunstify -t 1000 -p -r $ID -i $ICON "Backlight" " $TEXT" >/home/brian/.config/.dunst_backlight
else
 dunstify -t 1000 -p -i $ICON "Backlight" " $TEXT" >/home/brian/.config/.dunst_backlight
fi
