#!/bin/bash

if [ $1 == "mute" ]
then
	pactl set-sink-mute 0 toggle
	if [ $(pactl list sinks | grep Mute | awk '{print $2}') == "no" ]
	then
		ICON="/usr/share/icons/breeze-dark/actions/24/audio-volume-high.svg "
		TITLE="Unmuted"
	else
		ICON="/usr/share/icons/breeze-dark/actions/24/audio-volume-muted.svg "
		TITLE="Muted"
fi

else if [ $1 == "up" ]
then
	pactl set-sink-mute 0 0
	pactl set-sink-volume 0 +5%
	TITLE="Volume"
	ICON="/usr/share/icons/breeze-dark/actions/24/audio-volume-high.svg "
else if [ $1 == "down" ]
then
	pactl set-sink-mute 0 0
	pactl set-sink-volume 0 -5%
	TITLE="Volume"
	ICON="/usr/share/icons/breeze-dark/actions/24/audio-volume-medium.svg "
else
	exit 1
fi
fi
fi

ID=$(cat /home/brian/.config/.dunst_volume)
TEXT=$(pactl list sinks | grep "Volume: f" | awk '{print $5}')
if [ $ID -gt "0" ]
then
 dunstify  -p -t 1000 -r $ID -i $ICON "$TITLE" " $TEXT"  >/home/brian/.config/.dunst_volume
else
 dunstify  -p -t 1000 -i $ICON "$TITLE" " $TEXT"  >/home/brian/.config/.dunst_volume
fi
