#!/bin/bash

pactl set-sink-mute 0 toggle
TEXT=$(pactl list sinks | grep "Volume: f" | awk '{print $5}')
ID=$(cat /home/brian/.config/.dunst_volume)
ICON="/usr/share/icons/breeze-dark/actions/24/audio-volume-muted.svg "
if [ $ID -gt "0" ]
then
 dunstify -p -r $ID -i $ICON "Volume: $TEXT" >/home/brian/.config/.dunst_volume
else
 dunstify -p -i $ICON "Volume: $TEXT" >/home/brian/.config/.dunst_volume
fi
