#!/bin/bash

#playerctl echos when there's no player instead of writing to standard out
#making that error text invisible
echo -n "%{F#00000000}"

STR="%{F#30ffff}$(playerctl  metadata artist)%{F-} $(playerctl metadata title)"
echo "$STR"
exit
